import type { DeveloperPersonality, RepositoryProfileView } from "./product-types";

export const demoPersonality: DeveloperPersonality = {
  archetype: "Experimental Systems Architect",
  summary:
    "You build fast, connect strange ideas, and prototype like deadlines are optional social constructs. You match best with active devtool, AI, and creative coding repositories that need exploratory energy without total collapse.",
  strengths: ["rapid prototyping", "creative abstractions", "AI/devtool instincts", "interactive systems thinking"],
  risks: ["scope drift", "aggressive iteration cycles", "may start three projects before stabilizing one"],
  preferredLanguages: ["TypeScript", "Python", "Rust"],
  preferredStacks: ["AI tooling", "local-first apps", "creative devtools"],
  architectureTendency: "Composable first, dramatic refactor second.",
  collaborationStyle: "Async-first, screenshot-heavy, mildly allergic to vague issues.",
  compatibilityStyle: "Best with active maintainers, clear issues, and repos that need useful chaos.",
  representativeRepos: [
    { name: "vector-lab/sidequest", language: "TypeScript", reason: "experimental interface work", tag: "prototype spark" },
    { name: "tiny-oracle/cli", language: "Rust", reason: "systems curiosity with sharp edges", tag: "terminal romance" },
    { name: "sketch-runtime/play", language: "Python", reason: "AI workflows and unusual tools", tag: "model whisperer" },
  ],
};

export const demoRepositories: RepositoryProfileView[] = [
  {
    id: "demo-open-webui",
    githubId: 1,
    name: "open-webui",
    owner: "open-webui",
    fullName: "open-webui/open-webui",
    description: "User-friendly AI interface for running and managing local and hosted language models.",
    avatarUrl: "https://avatars.githubusercontent.com/u/158137808?v=4",
    ownerAvatarUrl: "https://avatars.githubusercontent.com/u/158137808?v=4",
    bannerUrl: "https://opengraph.githubassets.com/mergeconflict/open-webui/open-webui",
    githubUrl: "https://github.com/open-webui/open-webui",
    issuesUrl: "https://github.com/open-webui/open-webui/issues",
    primaryLanguage: "TypeScript",
    languageColor: "#3178c6",
    stars: 94000,
    forks: 12000,
    openIssues: 1200,
    contributors: 400,
    goodFirstIssues: 18,
    lastUpdated: "Recently",
    license: "BSD-3-Clause",
    topics: ["AI", "LLM", "Chat", "Self-hosted"],
    techStack: ["TypeScript", "Python", "Docker", "Svelte"],
    compatibility: 87,
    onboardingDifficulty: "Medium",
    activityLevel: "Chaotic",
    documentationQuality: "Good",
    maintainerVibe: "ambitious, fast-moving, allergic to stagnation",
    contributorCulture: "builders who can keep up with rapid product changes",
    personalityLine: "Fast-moving AI cockpit with chaotic brilliance.",
    aiPersonaTagline: "I am your local AI cockpit, and yes, my issue tracker is breathing.",
    readmeSummary: "A self-hosted AI web interface focused on model management, chat workflows, and extensibility.",
    greenFlags: ["active community", "high user demand", "lots of contribution surface"],
    redFlags: ["fast-changing architecture", "large issue volume", "setup may be nontrivial"],
    suggestedFirstContribution: "Improve onboarding docs or fix a UI bug with screenshots.",
    whyYouMatch: "You build AI-flavored tools and enjoy experimental interfaces. This repo rewards fast product instincts.",
    repoLoveLanguage: "Small PRs that make the product easier for real users.",
  },
  {
    id: "demo-vercel-ai",
    githubId: 2,
    name: "ai",
    owner: "vercel",
    fullName: "vercel/ai",
    description: "A toolkit for building AI-powered applications with streaming, tools, and structured outputs.",
    avatarUrl: "https://avatars.githubusercontent.com/u/14985020?v=4",
    ownerAvatarUrl: "https://avatars.githubusercontent.com/u/14985020?v=4",
    bannerUrl: "https://opengraph.githubassets.com/mergeconflict/vercel/ai",
    githubUrl: "https://github.com/vercel/ai",
    issuesUrl: "https://github.com/vercel/ai/issues",
    primaryLanguage: "TypeScript",
    languageColor: "#3178c6",
    stars: 21000,
    forks: 3200,
    openIssues: 420,
    contributors: 310,
    goodFirstIssues: 9,
    lastUpdated: "Recently",
    license: "Apache-2.0",
    topics: ["AI", "SDK", "Streaming", "Agents"],
    techStack: ["TypeScript", "React", "Next.js"],
    compatibility: 91,
    onboardingDifficulty: "Hard",
    activityLevel: "High",
    documentationQuality: "Excellent",
    maintainerVibe: "precise, fast, allergic to fuzzy abstractions",
    contributorCulture: "PRs with examples, tests, and clean mental models",
    personalityLine: "Elegant AI infrastructure that expects you to read the room and the types.",
    aiPersonaTagline: "Bring tests, bring examples, bring emotional readiness for streaming edge cases.",
    readmeSummary: "Core primitives for AI app development across providers, interfaces, and streaming workflows.",
    greenFlags: ["strong docs", "real users", "clear product gravity"],
    redFlags: ["high standards", "fast API evolution", "requires context"],
    suggestedFirstContribution: "Add an example app or clarify a provider edge case.",
    whyYouMatch: "Your TypeScript and AI-tool instincts are suspiciously aligned with this ecosystem.",
    repoLoveLanguage: "Tiny focused changes that make advanced flows feel obvious.",
  },
  {
    id: "demo-rustlings",
    githubId: 3,
    name: "rustlings",
    owner: "rust-lang",
    fullName: "rust-lang/rustlings",
    description: "Small exercises to get you used to reading and writing Rust code.",
    avatarUrl: "https://avatars.githubusercontent.com/u/5430905?v=4",
    ownerAvatarUrl: "https://avatars.githubusercontent.com/u/5430905?v=4",
    bannerUrl: "https://opengraph.githubassets.com/mergeconflict/rust-lang/rustlings",
    githubUrl: "https://github.com/rust-lang/rustlings",
    issuesUrl: "https://github.com/rust-lang/rustlings/issues",
    primaryLanguage: "Rust",
    languageColor: "#dea584",
    stars: 61000,
    forks: 11000,
    openIssues: 180,
    contributors: 230,
    goodFirstIssues: 35,
    lastUpdated: "Recently",
    license: "MIT",
    topics: ["Rust", "Education", "CLI", "Beginner"],
    techStack: ["Rust", "CLI", "Exercises"],
    compatibility: 66,
    onboardingDifficulty: "Easy",
    activityLevel: "Medium",
    documentationQuality: "Excellent",
    maintainerVibe: "patient, exact, spiritually linted",
    contributorCulture: "small fixes, gentle pedagogy, respect for learners",
    personalityLine: "Beginner-friendly until your compiler feelings become textual evidence.",
    aiPersonaTagline: "I teach Rust one tiny compiler complaint at a time.",
    readmeSummary: "A curated exercise set for learning Rust through practical fixes and guided errors.",
    greenFlags: ["great first issues", "clear purpose", "low setup drama"],
    redFlags: ["education quality bar", "small changes need care", "Rust will perceive you"],
    suggestedFirstContribution: "Clarify an exercise hint or improve a learner-facing error message.",
    whyYouMatch: "Your systems curiosity could become useful if pointed at teaching instead of reinvention.",
    repoLoveLanguage: "Kind explanations that make hard concepts feel survivable.",
  },
];
