export const developerPersonality = {
  archetype: 'Experimental Systems Architect',
  summary:
    'You build fast, connect strange ideas, and prototype like deadlines are optional social constructs. You match best with active devtool, AI, and creative coding repositories that need exploratory energy without total collapse.',
  strengths: ['rapid prototyping', 'creative abstractions', 'AI/devtool instincts', 'interactive systems thinking'],
  risks: ['unfinished scaling patterns', 'aggressive iteration cycles', 'may start three projects before stabilizing one'],
  preferredLanguages: ['TypeScript', 'Python', 'Rust'],
  preferredStacks: ['AI tooling', 'local-first apps', 'creative devtools'],
  architectureTendency: 'Modular until inspired, then suspiciously theatrical.',
  collaborationStyle: 'Async-first, screenshot-heavy, mildly allergic to vague issues.',
  compatibilityStyle:
    'Works best with stabilizers, maintainers, and repos that need chaotic creative energy without architecture soup.',
  representativeRepos: [
    { name: 'vector-lab/sidequest', language: 'TypeScript', reason: 'experimental interface work', tag: 'prototype spark' },
    { name: 'tiny-oracle/cli', language: 'Rust', reason: 'systems curiosity with sharp edges', tag: 'terminal romance' },
    { name: 'sketch-runtime/play', language: 'Python', reason: 'AI workflows and unusual tools', tag: 'model whisperer' }
  ]
};

export const repos = [
  {
    id: 'open-webui',
    name: 'open-webui',
    owner: 'open-webui',
    fullName: 'open-webui/open-webui',
    description: 'User-friendly AI interface for running and managing local and hosted language models.',
    githubUrl: 'https://github.com/open-webui/open-webui',
    issuesUrl: 'https://github.com/open-webui/open-webui/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 94000,
    forks: 12000,
    openIssues: 1200,
    contributors: 400,
    goodFirstIssues: 18,
    lastUpdated: 'Recently',
    license: 'BSD-3-Clause',
    topics: ['AI', 'LLM', 'Chat', 'Self-hosted'],
    techStack: ['TypeScript', 'Python', 'Docker', 'Svelte'],
    compatibility: 87,
    onboardingDifficulty: 'Medium',
    activityLevel: 'Chaotic',
    documentationQuality: 'Good',
    maintainerVibe: 'ambitious, fast-moving, allergic to stagnation',
    contributorCulture: 'builders who can keep up with rapid product changes',
    personalityLine: 'Fast-moving AI cockpit with chaotic brilliance.',
    aiPersonaTagline: 'I am your local AI cockpit, and yes, my issue tracker is breathing.',
    readmeSummary: 'A self-hosted AI web interface focused on model management, chat workflows, and extensibility.',
    greenFlags: ['active community', 'high user demand', 'lots of contribution surface'],
    redFlags: ['fast-changing architecture', 'large issue volume', 'setup may be nontrivial'],
    suggestedFirstContribution: 'Improve onboarding docs or fix a UI bug with screenshots.',
    whyYouMatch: 'You build AI-flavored tools and enjoy experimental interfaces. This repo rewards fast product instincts.',
    repoLoveLanguage: 'Small PRs that make the product easier for real users.'
  },
  {
    id: 'vercel-ai',
    name: 'ai',
    owner: 'vercel',
    fullName: 'vercel/ai',
    description: 'A toolkit for building AI-powered applications with streaming, tools, and structured outputs.',
    githubUrl: 'https://github.com/vercel/ai',
    issuesUrl: 'https://github.com/vercel/ai/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 21000,
    forks: 3200,
    openIssues: 420,
    contributors: 310,
    goodFirstIssues: 9,
    lastUpdated: 'Recently',
    license: 'Apache-2.0',
    topics: ['AI', 'SDK', 'Streaming', 'Agents'],
    techStack: ['TypeScript', 'React', 'Next.js'],
    compatibility: 91,
    onboardingDifficulty: 'Hard',
    activityLevel: 'High',
    documentationQuality: 'Excellent',
    maintainerVibe: 'precise, fast, allergic to fuzzy abstractions',
    contributorCulture: 'PRs with examples, tests, and clean mental models',
    personalityLine: 'Elegant AI infrastructure that expects you to read the room and the types.',
    aiPersonaTagline: 'Bring tests, bring examples, bring emotional readiness for streaming edge cases.',
    readmeSummary: 'Core primitives for AI app development across providers, interfaces, and streaming workflows.',
    greenFlags: ['strong docs', 'real users', 'clear product gravity'],
    redFlags: ['high standards', 'fast API evolution', 'requires context'],
    suggestedFirstContribution: 'Add an example app or clarify a provider edge case.',
    whyYouMatch: 'Your TypeScript and AI-tool instincts are suspiciously aligned with this ecosystem.',
    repoLoveLanguage: 'Tiny focused changes that make advanced flows feel obvious.'
  },
  {
    id: 'excalidraw',
    name: 'excalidraw',
    owner: 'excalidraw',
    fullName: 'excalidraw/excalidraw',
    description: 'Virtual whiteboard for sketching hand-drawn-like diagrams and collaborative ideas.',
    githubUrl: 'https://github.com/excalidraw/excalidraw',
    issuesUrl: 'https://github.com/excalidraw/excalidraw/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 89000,
    forks: 8300,
    openIssues: 760,
    contributors: 260,
    goodFirstIssues: 22,
    lastUpdated: 'Recently',
    license: 'MIT',
    topics: ['Canvas', 'Collaboration', 'Drawing', 'Productivity'],
    techStack: ['TypeScript', 'React', 'Canvas'],
    compatibility: 84,
    onboardingDifficulty: 'Medium',
    activityLevel: 'High',
    documentationQuality: 'Good',
    maintainerVibe: 'design-sensitive and quietly intense',
    contributorCulture: 'visual polish, careful UX, and screenshots or it did not happen',
    personalityLine: 'A creative coding sweetheart with strong opinions about pixels.',
    aiPersonaTagline: 'I draw boxes around your ideas and your architectural avoidance.',
    readmeSummary: 'A collaborative sketching app with rich canvas interactions and a beloved visual style.',
    greenFlags: ['clear product identity', 'visible impact', 'friendly issues'],
    redFlags: ['UI details matter', 'canvas bugs hide in corners', 'large surface area'],
    suggestedFirstContribution: 'Polish a small interaction bug and include before/after captures.',
    whyYouMatch: 'You like expressive interfaces and tools that make technical work feel playful.',
    repoLoveLanguage: 'Thoughtful UX fixes with proof that the interaction still feels good.'
  },
  {
    id: 'supabase',
    name: 'supabase',
    owner: 'supabase',
    fullName: 'supabase/supabase',
    description: 'Open source Firebase alternative with databases, auth, storage, edge functions, and more.',
    githubUrl: 'https://github.com/supabase/supabase',
    issuesUrl: 'https://github.com/supabase/supabase/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 76000,
    forks: 8200,
    openIssues: 980,
    contributors: 620,
    goodFirstIssues: 31,
    lastUpdated: 'Recently',
    license: 'Apache-2.0',
    topics: ['Database', 'Auth', 'Postgres', 'Platform'],
    techStack: ['TypeScript', 'Postgres', 'Go', 'Elixir'],
    compatibility: 72,
    onboardingDifficulty: 'Hard',
    activityLevel: 'High',
    documentationQuality: 'Excellent',
    maintainerVibe: 'platform-minded, practical, relentlessly shipping',
    contributorCulture: 'deep systems work with strong docs empathy',
    personalityLine: 'A full platform that can love you back, after local setup negotiates terms.',
    aiPersonaTagline: 'I contain multitudes, mostly Postgres-shaped.',
    readmeSummary: 'A large platform bringing backend primitives together in an open source developer experience.',
    greenFlags: ['huge ecosystem', 'good docs', 'many contribution paths'],
    redFlags: ['big codebase', 'multi-language complexity', 'setup can sprawl'],
    suggestedFirstContribution: 'Improve a docs path or fix a dashboard papercut.',
    whyYouMatch: 'You can navigate product and infrastructure without pretending they are separate planets.',
    repoLoveLanguage: 'Clear reproduction steps and changes that reduce developer confusion.'
  },
  {
    id: 'rustlings',
    name: 'rustlings',
    owner: 'rust-lang',
    fullName: 'rust-lang/rustlings',
    description: 'Small exercises to get you used to reading and writing Rust code.',
    githubUrl: 'https://github.com/rust-lang/rustlings',
    issuesUrl: 'https://github.com/rust-lang/rustlings/issues',
    primaryLanguage: 'Rust',
    languageColor: '#dea584',
    stars: 61000,
    forks: 11000,
    openIssues: 180,
    contributors: 230,
    goodFirstIssues: 35,
    lastUpdated: 'Recently',
    license: 'MIT',
    topics: ['Rust', 'Education', 'CLI', 'Beginner'],
    techStack: ['Rust', 'CLI', 'Exercises'],
    compatibility: 66,
    onboardingDifficulty: 'Easy',
    activityLevel: 'Medium',
    documentationQuality: 'Excellent',
    maintainerVibe: 'patient, exact, spiritually linted',
    contributorCulture: 'small fixes, gentle pedagogy, respect for learners',
    personalityLine: 'Beginner-friendly until your borrow checker feelings become textual evidence.',
    aiPersonaTagline: 'I teach Rust one tiny compiler complaint at a time.',
    readmeSummary: 'A curated exercise set for learning Rust through practical fixes and guided errors.',
    greenFlags: ['great first issues', 'clear purpose', 'low setup drama'],
    redFlags: ['education quality bar', 'small changes need care', 'Rust will perceive you'],
    suggestedFirstContribution: 'Clarify an exercise hint or improve a learner-facing error message.',
    whyYouMatch: 'Your systems curiosity could become useful if pointed at teaching instead of reinvention.',
    repoLoveLanguage: 'Kind explanations that make hard concepts feel survivable.'
  },
  {
    id: 'storybook',
    name: 'storybook',
    owner: 'storybookjs',
    fullName: 'storybookjs/storybook',
    description: 'Frontend workshop for building UI components and pages in isolation.',
    githubUrl: 'https://github.com/storybookjs/storybook',
    issuesUrl: 'https://github.com/storybookjs/storybook/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 86000,
    forks: 9300,
    openIssues: 1500,
    contributors: 1500,
    goodFirstIssues: 42,
    lastUpdated: 'Recently',
    license: 'MIT',
    topics: ['UI', 'Components', 'Testing', 'Design Systems'],
    techStack: ['TypeScript', 'React', 'Vite', 'Webpack'],
    compatibility: 79,
    onboardingDifficulty: 'Haunted',
    activityLevel: 'Chaotic',
    documentationQuality: 'Good',
    maintainerVibe: 'deeply componentized and occasionally surrounded by build tools',
    contributorCulture: 'framework empathy, careful repros, lots of examples',
    personalityLine: 'A design-system metropolis with many districts and a build-system basement.',
    aiPersonaTagline: 'I can isolate your components and also your unresolved feelings about bundlers.',
    readmeSummary: 'A mature UI component environment spanning frameworks, docs, tests, and workflows.',
    greenFlags: ['many entry points', 'huge impact', 'strong ecosystem'],
    redFlags: ['large monorepo', 'tooling complexity', 'issue volume'],
    suggestedFirstContribution: 'Fix docs or add a focused reproduction for a framework integration.',
    whyYouMatch: 'You like interface systems and do not immediately flee when tools have layers.',
    repoLoveLanguage: 'Minimal repros, framework context, and empathy for maintainers.'
  },
  {
    id: 'immich',
    name: 'immich',
    owner: 'immich-app',
    fullName: 'immich-app/immich',
    description: 'Self-hosted photo and video management solution.',
    githubUrl: 'https://github.com/immich-app/immich',
    issuesUrl: 'https://github.com/immich-app/immich/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 72000,
    forks: 3600,
    openIssues: 620,
    contributors: 310,
    goodFirstIssues: 14,
    lastUpdated: 'Recently',
    license: 'AGPL-3.0',
    topics: ['Photos', 'Self-hosted', 'Mobile', 'ML'],
    techStack: ['TypeScript', 'Dart', 'Postgres', 'Machine Learning'],
    compatibility: 74,
    onboardingDifficulty: 'Hard',
    activityLevel: 'High',
    documentationQuality: 'Good',
    maintainerVibe: 'product-focused, careful with user memories',
    contributorCulture: 'practical fixes that respect real personal data',
    personalityLine: 'A self-hosted memory vault with backend muscles and mobile feelings.',
    aiPersonaTagline: 'I store your photos and your deployment anxieties.',
    readmeSummary: 'A photo backup and management system with web, mobile, ML, and self-hosted infrastructure.',
    greenFlags: ['beloved product', 'real user need', 'clear UX impact'],
    redFlags: ['multi-platform', 'data sensitivity', 'setup needs care'],
    suggestedFirstContribution: 'Improve docs around setup, backup safety, or mobile UX papercuts.',
    whyYouMatch: 'You enjoy products where infrastructure and human emotion collide.',
    repoLoveLanguage: 'Reliability-minded PRs with empathy for real family photo libraries.'
  },
  {
    id: 'zed',
    name: 'zed',
    owner: 'zed-industries',
    fullName: 'zed-industries/zed',
    description: 'A high-performance multiplayer code editor from the creators of Atom and Tree-sitter.',
    githubUrl: 'https://github.com/zed-industries/zed',
    issuesUrl: 'https://github.com/zed-industries/zed/issues',
    primaryLanguage: 'Rust',
    languageColor: '#dea584',
    stars: 54000,
    forks: 3200,
    openIssues: 2300,
    contributors: 260,
    goodFirstIssues: 16,
    lastUpdated: 'Recently',
    license: 'GPL-3.0',
    topics: ['Editor', 'Rust', 'Collaboration', 'Performance'],
    techStack: ['Rust', 'GPUI', 'Tree-sitter'],
    compatibility: 81,
    onboardingDifficulty: 'Haunted',
    activityLevel: 'Chaotic',
    documentationQuality: 'Okay',
    maintainerVibe: 'performance-obsessed and visually exacting',
    contributorCulture: 'serious engineering, careful UX, sharp profiling',
    personalityLine: 'A Rust editor with multiplayer ambition and extremely high standards.',
    aiPersonaTagline: 'I open files quickly and expectations even faster.',
    readmeSummary: 'A modern code editor focused on speed, collaboration, and native interface engineering.',
    greenFlags: ['ambitious product', 'deep engineering', 'visible impact'],
    redFlags: ['complex internals', 'high bar', 'platform-specific edges'],
    suggestedFirstContribution: 'Tackle a focused UI bug or improve extension docs.',
    whyYouMatch: 'Your devtool instincts fit a code editor that wants contributors with taste and stamina.',
    repoLoveLanguage: 'Measured improvements with profiling notes and calm confidence.'
  },
  {
    id: 'shadcn-ui',
    name: 'ui',
    owner: 'shadcn-ui',
    fullName: 'shadcn-ui/ui',
    description: 'Beautifully designed components that you can copy and paste into your apps.',
    githubUrl: 'https://github.com/shadcn-ui/ui',
    issuesUrl: 'https://github.com/shadcn-ui/ui/issues',
    primaryLanguage: 'TypeScript',
    languageColor: '#3178c6',
    stars: 82000,
    forks: 5400,
    openIssues: 860,
    contributors: 250,
    goodFirstIssues: 20,
    lastUpdated: 'Recently',
    license: 'MIT',
    topics: ['Components', 'Design System', 'Tailwind', 'React'],
    techStack: ['TypeScript', 'React', 'Tailwind'],
    compatibility: 88,
    onboardingDifficulty: 'Medium',
    activityLevel: 'High',
    documentationQuality: 'Excellent',
    maintainerVibe: 'minimal, exacting, deeply allergic to visual noise',
    contributorCulture: 'design restraint, accessible defaults, practical examples',
    personalityLine: 'A component library that wants your UI to stop yelling.',
    aiPersonaTagline: 'I am copy-pasteable, but my standards are not optional.',
    readmeSummary: 'A registry of composable components designed for ownership, accessibility, and product polish.',
    greenFlags: ['clear patterns', 'huge adoption', 'visual quality'],
    redFlags: ['taste matters', 'API churn around ecosystem', 'many duplicate requests'],
    suggestedFirstContribution: 'Add an example, improve accessibility notes, or polish docs.',
    whyYouMatch: 'You care about interactions that feel premium without becoming decorative soup.',
    repoLoveLanguage: 'Concise improvements that make teams ship better UI.'
  },
  {
    id: 'penpot',
    name: 'penpot',
    owner: 'penpot',
    fullName: 'penpot/penpot',
    description: 'Open source design and prototyping platform for product teams.',
    githubUrl: 'https://github.com/penpot/penpot',
    issuesUrl: 'https://github.com/penpot/penpot/issues',
    primaryLanguage: 'Clojure',
    languageColor: '#db5855',
    stars: 37000,
    forks: 2100,
    openIssues: 940,
    contributors: 170,
    goodFirstIssues: 11,
    lastUpdated: 'Recently',
    license: 'MPL-2.0',
    topics: ['Design', 'Prototyping', 'SVG', 'Open Source'],
    techStack: ['Clojure', 'ClojureScript', 'Postgres', 'SVG'],
    compatibility: 68,
    onboardingDifficulty: 'Hard',
    activityLevel: 'High',
    documentationQuality: 'Good',
    maintainerVibe: 'mission-driven, design-aware, quietly formidable',
    contributorCulture: 'patient contributors who like product depth',
    personalityLine: 'A design tool with open source ideals and a functional programming accent.',
    aiPersonaTagline: 'I make prototypes and occasionally ask if your editor supports paredit.',
    readmeSummary: 'A full design platform for teams that want open workflows and browser-based design tooling.',
    greenFlags: ['meaningful mission', 'rich product', 'clear visual domain'],
    redFlags: ['unusual stack', 'large app', 'design details matter'],
    suggestedFirstContribution: 'Improve a UI detail or help documentation around contributor setup.',
    whyYouMatch: 'You like expressive tools, but this stack may ask whether you are serious.',
    repoLoveLanguage: 'Respect for product craft and willingness to learn the stack.'
  }
];
